### ISSUE TITLE
Doesn't work with stencil web component

### ISSUE THREAD

**Issue by jpzwarte** [chromaui/storybook-addon-pseudo-states#2]
- Stencil does as many things asynchronous as it can; This requires use of `setTimeout` instead of `requestAnimationFrame` at https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/src/withPseudoState.js#L118 ; that gives stencil time to initialise
- Still unclear to me, but it never reaches `if (shadowRoot) shadowHosts.add(shadowRoot.host);` for my web component
- It seems to throw an exception on the `sheet.insertRule(newRule, index);` line; `newRule = ":host(:active), :host(.pseudo-active) :host(), :host(:focus), :host(.pseudo-focus) :host() { outline: currentcolor none medium; }"`, `index = 4`, `"An invalid or illegal string was specified"`; the original `cssText = ":host(:active), :host(:focus) { outline: currentcolor none medium; }"`

**Comment by ghengeveld** [comment]
Could you add a story for this stencil component so I can debug?

**Comment by ghengeveld** [comment]
@jpzwarte Is this still an issue? I'm happy to accept a PR for Stencil support, but can't devote any time to it myself. Closing this issue because it's been stale for a long time.
