### ISSUE TITLE
Using the dropdown doesn't affect class names on the story container but story parameter does.

### ISSUE THREAD

**Issue by henrikhansson** [chromaui/storybook-addon-pseudo-states#27]
Using the dropdown doesn't affect class names on the story container, no matter what state or combination is selected. However, using the story parameter works flawlessly. Am I missing something obvious here? Since it's working with parameters I assume that the plugin and Storybook is installed correctly.

Using `@storybook/vue 6.4.22`

**Comment by ghengeveld** [comment]
This was a bug in an earlier version of the addon, which has since been resolved.
