### ISSUE TITLE
Storybook 6.5 peerDependencies react 18.1.0

### ISSUE THREAD

**Issue by dutscher** [chromaui/storybook-addon-pseudo-states#32]
With the new 6.5.x Storybook release and your package as dependency will break the 'npm install'.
Due the addons with ' || ^18.0.0' in it comes react '18.1.0' but your plugin dont accept that.

https://github.com/chromaui/storybook-addon-pseudo-states/blob/d58f2f794da324d0ebaa87a0bedb10f21119dd47/package.json#L58
```
    "react": "^16.8.0 || ^17.0.0",
    "react-dom": "^16.8.0 || ^17.0.0"
```
https://github.com/storybookjs/storybook/blob/4b849f9bcd1d76bd6a016d50f7f1cb8f7809ed31/lib/addons/package.json#L55
```
    "react": "^16.8.0 || ^17.0.0 || ^18.0.0",
    "react-dom": "^16.8.0 || ^17.0.0 || ^18.0.0"
```

or maybe i'm wrong :D 

cheers

**Comment by KorySchneider** [comment]
@chromaui Any movement on this?
