### ISSUE TITLE
How do you get this to work?

### ISSUE THREAD

**Issue by abrahym-sharfeldden** [chromaui/storybook-addon-pseudo-states#33]
Hi, I followed the README.MD and it's set up but what do I code to toggle between the states?

**Comment by ghengeveld** [comment]
There's a toolbar icon you can use to toggle the states.

**Comment by abrahym-sharfeldden** [comment]
So you simply set the states with CSS and it automatically does the toggling?

**Comment by ghengeveld** [comment]
Yes, just install the addon and use the toolbar to select the state you want to see, or add `parameters` to your stories to give them an initial pseudo state. You can also wrap your story components in a div with e.g. `pseudo-hover` class on it. See https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/stories/Button.stories.js
