### ISSUE TITLE
DOMException: Failed to execute 'insertRule' on webkit rules

### ISSUE THREAD

**Issue by brutus-law** [chromaui/storybook-addon-pseudo-states#37]
Was trying out this plugin so I'm on version 1.15.1 but getting the following errors. "@storybook/react": "^6.5.9",
`
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule 'body ::-webkit-scrollbar-thumb:hover, body ::-webkit-scrollbar-thumb.pseudo-hover, .pseudo-hover body ::-webkit-scrollbar-thumb { background: rgba(128, 135, 139, 0.8); }'.
`

`
DOMException: Failed to execute 'insertRule' on 'CSSStyleSheet': Failed to parse the rule '.custom-range::-webkit-slider-thumb:active, .custom-range::-webkit-slider-thumb.pseudo-active, .pseudo-active .custom-range::-webkit-slider-thumb { background-color: rgb(255, 230, 224); }'.
`

![image](https://user-images.githubusercontent.com/98431589/181066515-adfdb6e5-5230-4e4a-a584-a2c78fcd280e.png)
![image](https://user-images.githubusercontent.com/98431589/181066935-17980ced-51f2-4822-9ffd-309b5a451582.png)

**Comment by DmSor** [comment]
Having the same problem with
-webkit-datetime-edit-hour-field,
-webkit-datetime-edit-minute-field,
-webkit-datetime-edit-second-field.
I think the issue is not solved.

**Comment by ghengeveld** [comment]
@m-akinc Did you consider these by any chance?
