### ISSUE TITLE
[Feature request] Target only specific elements with the hover-state

### ISSUE THREAD

**Issue by davidfloegel** [chromaui/storybook-addon-pseudo-states#4]
Hey!

Great plugin, already wrote tons of stories that finally need to have their pseudo states checked :)

One feature idea I had was being able to target just a specific element rather than activating the pseudo-state on all elements.

A good example for this would be a `Select` or a `List`.

```
[ List item 1 ]
[ List item 2 ]
[ List item 3 ]
[ List item 4 ]
```

If I want to check that an element has the correct hover state, I kinda just want to activate it on one item.

I'm not sure how that'd look in an implementation, but I think we might need to be able to get our hands on the `WithPseudoState` and wrap it around specific components, i.e.
```
<WithPseudoState state="hover" target="[data-testid=3]">
  <List
    items={[
      { id: 1, label: 'Item 1' },
      { id: 2, label: 'Item 2' },
      { id: 3, label: 'Item 3' },
      { id: 4, label: 'Item 4' },
    ]}
  />
</WithPseudoState>
```

I've completely made this up but maybe something along those lines could work?

Thanks a lot!

**Comment by SimeonRolev** [comment]
Useful idea! Being able to display multiple states in a single story is useful for previewing at-a-glance and for Chromatic snapshots. Is this feature being developed?

**Comment by sag1v** [comment]
I've opened a PR to support it #25
