### ISSUE TITLE
pseudo-state rules passed to a scss media query mixin do not appear to be added to the DOM

### ISSUE THREAD

**Issue by calebtr-metro** [chromaui/storybook-addon-pseudo-states#41]
`:hover` definitions defined in scss and passed through to a media query mixin via`@include` and `@content` do not appear to be added to the DOM.

I am using:

├── @storybook/html@6.5.12
├── storybook-addon-pseudo-states@1.15.1

The storybook bits work great, thank you. The `pseudo-class` class is added where I want it, but the related CSS definition is not added to the DOM.

Works:
```
.component:hover {
    background-color: purple;
}
```

Does not work:
```
@include medium {
    .component:hover {
        background-color: purple;
    }
}
```

Where mixins have been previously defined:

```
@mixin medium {
  @include breakpoint(777px) {
    @content;
  }
}

@mixin breakpoint($breakpoint) {
  @media (min-width: #{$breakpoint}) {
    @content;
  }
}
```

I'm not sure if this has to do with the rules being inside a mixin, a media query, or what.

**Comment by yuriystasiv** [comment]
I have the same problem, is there any information if this will be fixed in the near future?
