### ISSUE TITLE
Module parse failed when adding the addon

### ISSUE THREAD

**Issue by galexandrade** [chromaui/storybook-addon-pseudo-states#50]
I am trying to use the addon following the https://storybook.js.org/addons/storybook-addon-pseudo-states steps but, I'm getting this error when running storybook:

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/24475665/210629708-c10f2778-479a-4aa7-96af-7a621ea40ae6.png">

I am running on these versions:
- "@storybook/react": "^6.5.15",
- "react": "^16.13.1",
- "react-dom": "^16.13.1"

Not sure what is going on.

**Comment by sag1v** [comment]
Duplicate of #48

**Comment by galexandrade** [comment]
Oh ok. Closing this since there is already a ticket for it.
