### ISSUE TITLE
Selecting specific element also applies pseudostate to all its descendants

### ISSUE THREAD

**Issue by filipw01** [chromaui/storybook-addon-pseudo-states#56]
Because of this rewrite logic if `.pseudo-*` class is applied to a specific element it triggers all descendants' pseudostate
https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/src/rewriteStyleSheet.test.js#L26-L30

when: `parameters = { pseudo: { hover: '.someSelector' } }` or `parameters = { pseudo: { hover: ['.someSelector', 'div'] } }`

Current state:
`a:hover` -> `a:hover, a.pseudo-hover, .pseudo-hover a`

Proposed change:
`a:hover` -> `a:hover, a.pseudo-hover`

when: `parameters = { pseudo: { hover: true } }`

no changes - `a:hover` -> `a:hover, a.pseudo-hover, .pseudo-hover a`

**Comment by filipw01** [comment]
I can work on this, just want to confirm that this is a valid option that you want to implement 😄

**Comment by filipw01** [comment]
@ghengeveld What do you think about it?

**Comment by poalrom** [comment]
Hi! We faced the same issue with pseudostates and snapshotting with Chromatic. Play functions are not working for us (esp with hover) and this addon is the only solution. @ghengeveld, can you take a look, please?

**Comment by poalrom** [comment]
@ghengeveld I can add this functionality, but I think it will break backward compatibility. Is it ok to up to a major version or it's better to add a different way to enable this behaviour?

**Comment by JonathanKolnik** [comment]
I'm starting this today

**Comment by JonathanKolnik** [comment]
You can use the canary version here https://www.npmjs.com/package/storybook-addon-pseudo-states/v/2.1.1--canary.85.01f67b4.0, I am still working on support for custom elements but it should work otherwise. Please let me know if you have any feedback #85

**Comment by thafryer** [comment]
^^ @poalrom @filipw01

**Comment by JonathanKolnik** [comment]
I'm closing this issue because it has been fixed and is now available in v2.1.1
