### ISSUE TITLE
Attempted to set a global (pseudo) that is not defined in initial globals or globalTypes

### ISSUE THREAD

**Issue by sgoodluck** [chromaui/storybook-addon-pseudo-states#59]
When spinning up storybook 7.0.0 (beta) I'm unable to use this package successfully. Any attempt to use the menu results in the above console output.

Would love any recommendations!

**Comment by srMarquinho** [comment]
I've managed to get it working defining pseudo as a global type:
```ts
// preview.ts/js
const preview: Preview = {
  globalTypes: {
    pseudo: {}
  },
  ...
};
export default preview;
```

**Comment by richbachman** [comment]
@srMarquinho tried that approach with luck. I do have a different error now:

```
Uncaught TypeError: Cannot read properties of null (reading 'className')
    at applyClasses (withPseudoState.js:12:1)
    at withPseudoState.js:33:1
    at Map.forEach (<anonymous>)
    at applyParameter (withPseudoState.js:30:1)
    at withPseudoState.js:80:1
```

**Comment by srMarquinho** [comment]
> @srMarquinho tried that approach with luck. I do have a different error now:
> 
> ```
> Uncaught TypeError: Cannot read properties of null (reading 'className')
>     at applyClasses (withPseudoState.js:12:1)
>     at withPseudoState.js:33:1
>     at Map.forEach (<anonymous>)
>     at applyParameter (withPseudoState.js:30:1)
>     at withPseudoState.js:80:1
> ```

@richbachman Unfortunately I  did not see that. I'm on:
```
"storybook": "^7.0.0-rc.10",
"storybook-addon-pseudo-states": "^2.0.0-next.3",

```

**Comment by richbachman** [comment]
@srMarquinho the `2.0.0-next.3` version was the ticket. Thanks for the tip!

**Comment by R-Lek** [comment]
It works with version `2.0.1` now as well.
Kudos to [srMarquinho](https://github.com/srMarquinho), I was stumped with this error until I found this issue.

**Comment by Sidnioulz** [comment]
Just to clarify, the warning is still being shown. If any add-on author knows how to register globals from within add-on code, could you please provide an example?

**Comment by Sidnioulz** [comment]
Looks like this issue can be closed! Thanks @yasnbouz for writing a fix!
