### ISSUE TITLE
Dynamically updated stylesheets may not have pseudo states applied

### ISSUE THREAD

**Issue by ghengeveld** [chromaui/storybook-addon-pseudo-states#86]
The addon currently processes every stylesheet in the document only once. It marks the stylesheet as "rewritten" and will never touch it again. However, sometimes a stylesheet might get updated dynamically, e.g. as a result of switching a theme global. In such cases any newly injected CSS rules will not get rewritten for pseudo states, because their parent stylesheet has been rewritten before.

Likely the solution would be to mark individual CSS rules as having been rewritten, rather than the stylesheet as a whole.

**Comment by Flirre** [comment]
Hopefully it's not rude to ask, but is there a timeline or estimation for when this would be done?

**Comment by ghengeveld** [comment]
Working on it today. Ran into a snag though, so this might need a little more work.

**Comment by ghengeveld** [comment]
Shipped in [v2.1.2](https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/CHANGELOG.md#v212-wed-oct-11-2023)
