### ISSUE TITLE
Support for CSS Cascade layers

### ISSUE THREAD

**Issue by TaneliTuomola** [chromaui/storybook-addon-pseudo-states#93]
The add-on does not work with CSS styles that are inside of CSS @layer -statement. Only base level cssRules are handled but not cssRules from CSSLayerBlockRule.

[https://developer.mozilla.org/en-US/docs/Web/CSS/@layer](https://developer.mozilla.org/en-US/docs/Web/CSS/@layer)
[https://developer.mozilla.org/en-US/docs/Web/API/CSSLayerBlockRule](https://developer.mozilla.org/en-US/docs/Web/API/CSSLayerBlockRule)

**Comment by ghengeveld** [comment]
I would be happy to review and merge a PR for this. Right now I can't prioritize working on this myself.

**Comment by smitev** [comment]
@ghengeveld any plans to look at this feature in near future?

**Comment by ghengeveld** [comment]
I don't have the bandwidth to do this right now. Happy to review and merge a PR though.

**Comment by m-akinc** [comment]
@ghengeveld I have put up PR #103 to address this and a number of shadow DOM problems. Please give it a review when you have the time. 😊

**Comment by m-akinc** [comment]
@smitev Yes, it should support any CSS [at-rules](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) which contain other rules in curly braces.

**Comment by smitev** [comment]
@ghengeveld you had a chance to look at #103 ?
Should we expect it in soon?

**Comment by ghengeveld** [comment]
@smitev It was released in [v2.2.0](https://github.com/chromaui/storybook-addon-pseudo-states/blob/main/CHANGELOG.md#v220-mon-mar-04-2024).
